udo: false

matrix:
    include:
    - os: linux
      language: java
      jdk:  oraclejdk8
      install: true
    - os: linux
      language: java
      jdk:  oraclejdk9
      install: true
    - os: linux
      language: java
      jdk:  oraclejdk10
      install: true
      
 #   - os: osx
 #     language: java
 #     osx_image: xcode9.2
 #     install: true
 #   - os: osx
 #     language: java
 #     osx_image: xcode9.2
 #     install: brew tap caskroom/cask && brew cask info java && brew cask reinstall java

cache:
  ccache: true
  directories:
   - /Users/travis/build/miho/
  
script:
    - cd VMF-Tutorial01 && ./gradlew run
    - cd VMF-Tutorial02 && ./gradlew run
    - cd VMF-Tutorial03 && ./gradlew run
    - cd VMF-Tutorial04 && ./gradlew run
    - cd VMF-Tutorial05 && ./gradlew run
    - cd VMF-Tutorial06 && ./gradlew run
