udo: false

matrix:
    include:
    - os: linux
      language: java
      jdk:  oraclejdk8
    - os: linux
      language: java
      jdk:  oraclejdk9
    - os: linux
      language: java
      jdk:  oraclejdk10
    - os: linux
      language: java
      jdk:  openjdk11
    - os: linux
      language: java
      jdk:  openjdk-ea
    allow_failures:
       - os: linux
         language: java
         jdk:  openjdk-ea
       - os: linux
         language: java
         jdk:  openjdk11
      
      
 #   - os: osx
 #     language: java
 #     osx_image: xcode9.2
 #     install: true
 #   - os: osx
 #     language: java
 #     osx_image: xcode9.2
 #     install: brew tap caskroom/cask && brew cask info java && brew cask reinstall java

cache:
  ccache: true
  directories:
   - /Users/travis/build/miho/
  
script:
    - export CWD=$(pwd)
    - cd $CWD/VMF-Tutorial-01 && ./gradlew run
    - cd $CWD/VMF-Tutorial-02 && ./gradlew run
    - cd $CWD/VMF-Tutorial-03 && ./gradlew run
    - cd $CWD/VMF-Tutorial-04 && ./gradlew run
    - cd $CWD/VMF-Tutorial-05 && ./gradlew run
