sudo: false

env:
  - TERM=dumb

matrix:
    include:
    - os: linux
      language: java
      jdk:  openjdk8
    - os: linux
      language: java
      jdk:  openjdk9
    - os: linux
      language: java
      jdk:  openjdk11
    - os: linux
      language: java
      jdk:  openjdk12
    - os: linux
      language: java
      jdk:  openjdk13
    - os: linux
      language: java
      jdk:  openjdk-ea
    allow_failures:
       - os: linux
         language: java
         jdk:  openjdk-ea
      
      
 #   - os: osx
 #     language: java
 #     osx_image: xcode9.2
 #     install: true
 #   - os: osx
 #     language: java
 #     osx_image: xcode9.2
 #     install: brew tap caskroom/cask && brew cask info java && brew cask reinstall java

# cache:
#   ccache: true
#   directories:
#    - /Users/travis/build/miho/
  
script:
    - export CWD=$(pwd)
    - cd $CWD/VMF-Tutorial-01 && ./gradlew run --stacktrace
    - cd $CWD/VMF-Tutorial-02 && ./gradlew run --stacktrace
    - cd $CWD/VMF-Tutorial-03 && ./gradlew run --stacktrace
    - cd $CWD/VMF-Tutorial-04 && ./gradlew run --stacktrace
    - cd $CWD/VMF-Tutorial-05 && ./gradlew run --stacktrace
    - cd $CWD/VMF-Tutorial-06 && ./gradlew run --stacktrace
    - cd $CWD/VMF-Tutorial-07 && ./gradlew run --stacktrace
    - cd $CWD/VMF-Tutorial-08 && ./gradlew run --stacktrace
    - cd $CWD/VMF-Tutorial-09 && ./gradlew run --stacktrace
    - cd $CWD/VMF-Tutorial-10 && ./gradlew run --stacktrace
    - cd $CWD/VMF-Tutorial-11 && ./gradlew run --stacktrace
    - cd $CWD/VMF-Tutorial-12 && ./gradlew run --stacktrace
    - cd $CWD/VMF-Tutorial-13 && ./gradlew run --stacktrace
