# Build worker image (VM template)
image: Visual Studio 2017

# scripts that are called at very beginning, before repo cloning
init:
  - date /T & time /T
  - git config --global core.autocrlf input
  - java -version

#branches:
#  only:
#  - master

clone_depth: 50

version: '{build}'

platform:
  - x64

configuration:
  - Release

environment:
  MSBUILD_FLAGS: /verbosity:minimal /maxcpucount
  matrix:
    - generator: "Visual Studio 15 2017 Win64"    

matrix:
  fast_finish: true

#cache:
#  - C:\projects\vmf-text\

build_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - cd VMF-Tutorial-01
  - gradlew.bat clean run --stacktrace
  - cd %APPVEYOR_BUILD_FOLDER%
  - cd VMF-Tutorial-02
  - gradlew.bat clean run --stacktrace
  - cd %APPVEYOR_BUILD_FOLDER%
  - cd VMF-Tutorial-03
  - gradlew.bat clean run --stacktrace
  - cd %APPVEYOR_BUILD_FOLDER%
  - cd VMF-Tutorial-04
  - gradlew.bat clean run --stacktrace
  - cd %APPVEYOR_BUILD_FOLDER%
  - cd VMF-Tutorial-05
  - gradlew.bat clean run --stacktrace
  - cd %APPVEYOR_BUILD_FOLDER%
